#Check if the user has authority to administrate MQ, using mqm if need to

QMGR1=QMANAGER1
QMGR1_IP=localhost
QMGR1_PORT=1111

QMGR2=QMANAGER2
QMGR2_IP=localhost
QMGR2_PORT=1112

principal=app

#Create a Queue Manager
crtmqm $QMGR1
crtmqm $QMGR2

#Start the Queue Manager
strmqm $QMGR1
strmqm $QMGR2

#Objects for $QMGR1
echo "DEFINE LISTENER(LISTENER.$QMGR1) TRPTYPE(TCP) PORT($QMGR1_PORT) CONTROL(QMGR)" | runmqsc $QMGR1
echo "START LISTENER(LISTENER.$QMGR1)" | runmqsc $QMGR1

echo "DEFINE CHANNEL(CHNL.$QMGR1) CHLTYPE(SVRCONN) TRPTYPE(TCP)" | runmqsc $QMGR1
echo "DEFINE QLOCAL(Q.$QMGR1)" | runmqsc $QMGR1

echo "DEFINE CHANNEL($QMGR1.$QMGR2) CHLTYPE(SDR) TRPTYPE(TCP) XMITQ(TRANSMIT.TO.$QMGR2) CONNAME('"${QMGR1_IP}"("${QMGR1_PORT}")')" | runmqsc $QMGR1

echo "DEFINE CHANNEL($QMGR2.$QMGR1) CHLTYPE(RCVR)" | runmqsc $QMGR1

echo "DEFINE CHANNEL(CHNL.$QMGR1) CHLTYPE(CLNTCONN) TRPTYPE(TCP) CONNAME($QMGR1_IP) QMNAME($QMGR1) DESCR('Client-connection to "${QMGR1}"')" | runmqsc $QMGR1

echo "DEFINE QLOCAL(TRANSMIT.TO.$QMGR2) DESCR('Default transmission queue to "${QMGR2}"') USAGE(XMITQ)" | runmqsc $QMGR1
echo "DEFINE QREMOTE(REMOTEQ.TO.$QMGR2) RNAME(Q$QMGR2) RQMNAME($QMGR2) XMITQ(TRANSMIT.TO.$QMGR2)" | runmqsc $QMGR1

echo "SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('"${principal}"') AUTHADD(ALL)" | runmqsc $QMGR1
echo "SET AUTHREC OBJTYPE(QUEUE) PROFILE('**') PRINCIPAL('"${principal}"') AUTHADD(ALL)" | runmqsc $QMGR1
echo "SET AUTHREC OBJTYPE(CHANNEL) PROFILE('**') PRINCIPAL('"${principal}"') AUTHADD(ALL)" | runmqsc $QMGR1


#Objects for $QMGR2
echo "DEFINE LISTENER(LISTENER.$QMGR2) TRPTYPE(TCP) PORT($QMGR2_PORT) CONTROL(QMGR)" | runmqsc $QMGR2
echo "START LISTENER(LISTENER.$QMGR2)" | runmqsc $QMGR2
echo "DEFINE CHANNEL(CHNL.$QMGR2) CHLTYPE(SVRCONN) TRPTYPE(TCP)" | runmqsc $QMGR2
echo "DEFINE QLOCAL(Q$QMGR2)" | runmqsc $QMGR2

echo "DEFINE CHANNEL($QMGR2.$QMGR1) CHLTYPE(SDR) TRPTYPE(TCP) XMITQ(TRANSMIT.TO.$QMGR1) CONNAME('"${QMGR2_IP}"("${QMGR2_PORT}")')" | runmqsc $QMGR2

echo "DEFINE CHANNEL($QMGR1.$QMGR2) CHLTYPE(RCVR)" | runmqsc $QMGR2

echo "DEFINE QLOCAL(TRANSMIT.TO.$QMGR1) DESCR('Default transmission queue to "${QMGR2}"') USAGE(XMITQ)" | runmqsc $QMGR2
echo "DEFINE QREMOTE(REMOTEQ.TO.$QMGR1) RNAME(Q$QMGR1) RQMNAME($QMGR1) XMITQ(TRANSMIT.TO.$QMGR1)" | runmqsc $QMGR2

echo "SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('"${principal}"') AUTHADD(ALL)" | runmqsc $QMGR2
echo "SET AUTHREC OBJTYPE(QUEUE) PROFILE('**') PRINCIPAL('"${principal}"') AUTHADD(ALL)" | runmqsc $QMGR2
echo "SET AUTHREC OBJTYPE(CHANNEL) PROFILE('**') PRINCIPAL('"${principal}"') AUTHADD(ALL)" | runmqsc $QMGR2


echo "START CHANNEL($QMGR2.$QMGR1)" | runmqsc $QMGR2




#Objects for $QMGR1
echo "START CHANNEL($QMGR1.$QMGR2)" | runmqsc $QMGR1