MQ Setup
========

#Check if the user has authority to administrate MQ, using mqm if need to



#Create a Queue Manager
crtmqm -q QM1
crtmqm -q QM2

#Start the Queue Manager
strmqm QM1
strmqm QM2

#Objects for QM1
runmqsc QM1

DEFINE LISTENER(LISTENER.QM1) TRPTYPE(TCP) PORT(1414)
START LISTENER(LISTENER.QM1)

DEFINE CHANNEL(CHNL.QM1) CHLTYPE(SVRCONN) TRPTYPE(TCP)
DEFINE QLOCAL(QQM1)

DEFINE CHANNEL (QM1.QM2) CHLTYPE(SDR) TRPTYPE(TCP) XMITQ(TRASMIT.TO.QM2) CONNAME('35.178.137.213(1414)')
START CHANNEL (QM1.QM2)

DEFINE QLOCAL (TRASMIT.TO.QM2) DESCR ('Default transmission queue to QM2') USAGE (XMITQ)
DEFINE QREMOTE (REMOTEQ.TO.QM2) RNAME (QQM2) RQMNAME (QM2) XMITQ (TRASMIT.TO.QM2)

SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('appuser') AUTHADD(ALL)
SET AUTHREC OBJTYPE(QUEUE) PROFILE('QQM1') PRINCIPAL('appuser') AUTHADD(ALL)
SET AUTHREC OBJTYPE(QUEUE) PROFILE('REMOTEQ.TO.QM2') PRINCIPAL('appuser') AUTHADD(ALL)
SET AUTHREC OBJTYPE(CHANNEL) PROFILE('**') PRINCIPAL('appuser') AUTHADD(ALL)

ALTER QMGR CONNAUTH(USE.PW)
DEFINE AUTHINFO(USE.PW) AUTHTYPE(IDPWOS) FAILDLAY(10) CHCKLOCL(OPTIONAL) CHCKCLNT(REQUIRED)
REFRESH SECURITY TYPE(CONNAUTH)

#Objects for QM2
runmqsc QM2

DEFINE LISTENER(LISTENER.QM2) TRPTYPE(TCP) PORT(1414)
START LISTENER(LISTENER.QM2)
DEFINE CHANNEL(CHNL.QM2) CHLTYPE(SVRCONN) TRPTYPE(TCP)
DEFINE QLOCAL(QQM2)

DEFINE CHANNEL (QM1.QM2) CHLTYPE(RCVR)

SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('appuser') AUTHADD(ALL)
SET AUTHREC OBJTYPE(QUEUE) PROFILE('QQM2') PRINCIPAL('appuser') AUTHADD(ALL)
SET AUTHREC OBJTYPE(CHANNEL) PROFILE('**') PRINCIPAL('appuser') AUTHADD(ALL)

ALTER QMGR CONNAUTH(USE.PW)
DEFINE AUTHINFO(USE.PW) AUTHTYPE(IDPWOS) FAILDLAY(10) CHCKLOCL(OPTIONAL) CHCKCLNT(REQUIRED)
REFRESH SECURITY TYPE(CONNAUTH)

DISPLAY QLOCAL(TRASMIT.TO.QM2) curdepth