MQ Setup
========

#Check if the user has authority to administrate MQ, using mqm if need to

QMGR1=QM1
QMGR1.IP=
QMGR1.PORT=

QMGR2=QM2
QMGR2.IP=

#Create a Queue Manager
crtmqm $QMGR1
crtmqm $QMGR2

#Start the Queue Manager
strmqm QMAJ
strmqm QMSK

#Objects for QMAJ
runmqsc QMAJ

DEFINE LISTENER(LISTENER.$QMGR2) TRPTYPE(TCP) PORT($QMGR1.PORT) CONTROL(QMGR)
START LISTENER(LISTENER.$QMGR2)

DEFINE CHANNEL(CHNL.$QMGR2) CHLTYPE(SVRCONN) TRPTYPE(TCP)
DEFINE QLOCAL(Q.$QMGR2)

DEFINE CHANNEL($QMGR2.QMSK) CHLTYPE(SDR) TRPTYPE(TCP) XMITQ(TRANSMIT.TO.QMSK) CONNAME('localhost(2001)')

DEFINE CHANNEL(QMSK.QMAJ) CHLTYPE(RCVR)


DEFINE CHANNEL(CHNL.AJ) CHLTYPE(CLNTCONN) TRPTYPE(TCP) CONNAME($QMGR2.IP) QMNAME(QMAJ) DESCR('Client-connection to QMAJ')

DEFINE QLOCAL(TRANSMIT.TO.QMSK) DESCR('Default transmission queue to QMSK') USAGE(XMITQ)
DEFINE QREMOTE(REMOTEQ.TO.QMSK) RNAME(QSK) RQMNAME(QMSK) XMITQ(TRANSMIT.TO.QMSK)

SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('app') AUTHADD(ALL)
SET AUTHREC OBJTYPE(QUEUE) PROFILE('**') PRINCIPAL('app') AUTHADD(ALL)
SET AUTHREC OBJTYPE(CHANNEL) PROFILE('**') PRINCIPAL('app') AUTHADD(ALL)


END

#Objects for QMSK
runmqsc QMSK

DEFINE LISTENER(LISTENER.SK) TRPTYPE(TCP) PORT(2001) CONTROL(QMGR)
START LISTENER(LISTENER.SK)
DEFINE CHANNEL(CHNL.SK) CHLTYPE(SVRCONN) TRPTYPE(TCP)
DEFINE QLOCAL(QSK)

DEFINE CHANNEL(QMSK.QMAJ) CHLTYPE(SDR) TRPTYPE(TCP) XMITQ(TRANSMIT.TO.QMAJ) CONNAME('localhost(1987)')

DEFINE CHANNEL(QMAJ.QMSK) CHLTYPE(RCVR)

DEFINE QLOCAL(TRANSMIT.TO.QMAJ) DESCR('Default transmission queue to QMSK') USAGE(XMITQ)
DEFINE QREMOTE(REMOTEQ.TO.QMAJ) RNAME(QAJ) RQMNAME(QMAJ) XMITQ(TRANSMIT.TO.QMAJ)

SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('app') AUTHADD(ALL)
SET AUTHREC OBJTYPE(QUEUE) PROFILE('**') PRINCIPAL('app') AUTHADD(ALL)
SET AUTHREC OBJTYPE(CHANNEL) PROFILE('**') PRINCIPAL('app') AUTHADD(ALL)


START CHANNEL(QMSK.QMAJ)
END

#Objects for QMSK
runmqsc QMAJ
START CHANNEL(QMAJ.QMSK)
END
